@startuml
'https://plantuml.com/sequence-diagram

autonumber

== load_file(file_name) ==

MyLLMSession -> MyLLMSession: text = clean_text(text)

alt#Gold #LightBlue text=chunk_text(text)
MyLLMSession -> RecursiveCharacterTextSplitter: chunks = split_text(text,chunk_size=1000,chunk_overlap=150 )

loop#LightGreen #LightYellow chunk in chunks
MyLLMSession -> OpenAIEmbeddings: chunk_encoded=encode(chunk)
note right
Generate tokens
for a given chunk of content
end note

MyLLMSession -> FAISS : add(chunk_encoded, chunk)
note right
Store
-embedding vector
-chunk
end note
end

end

@enduml